[application]
name = "Commission Manager"
client_id = "your_api_key"
application_url = "https://your-app.ngrok.io"
embedded = true

[application.pos]
embedded = false

[access_scopes]
scopes = "read_products,write_products,read_collections"

[auth]
redirect_urls = [
  "https://your-app.ngrok.io/api/auth/callback"
]

[webhooks]
api_version = "2023-10"