[application]
name = "Commission Manager"
client_id = "569e49e45bacbe4d8bc015d75300b96c"
application_url = "https://1c201aa997c4.ngrok-free.app"
embedded = true

[application.pos]
embedded = false

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://1c201aa997c4.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"